---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/labels.yaml@1e108b60c7de32c4bb02ad439c9a65368f55314e
